ce204_hw4_library.CarRentalSystem Class Reference
Public Member Functions
 loginPage
This the main class used to get details from the user and display the menu driven options This class acts as the businedd layer in our applications
void loginPage ()
 run
This the method called from main method this contains the menudriven interface to communicate with the user
void run ()
Static Public Attributes
static DateFormat format = new SimpleDateFormat(`dd/MM/yyyy`)
Detailed Description
Definition at line 11 of file CarRentalSystem.java.
Member Function Documentation
loginPage()
void ce204_hw4_library.CarRentalSystem.loginPage ()
Definition at line 24 of file CarRentalSystem.java.
                          {
    System.out.println("--------WELCOME---------");
    System.out.println("Press 1 for Sign In");
    System.out.println("Press 2 for Sign Up");
    System.out.print("--> ");
    int choice = scanner.nextInt();
    scanner.nextLine(); // Consume the newline character
    switch (choice) {
      case 1:
        if (signIn()) {
          run();
        } else {
          loginPage();
        }
        break;
      case 2:
        signUp();
        loginPage();
        break;
      default:
        System.out.println("Invalid choice. Please try again.");
        loginPage();
        break;
    }
  }
References ce204_hw4_library.CarRentalSystem.run().
Referenced by ce204_hw4_app.ce204_hw4_app.main(), and ce204_hw4_library.CarRentalSystem.run().
run()
void ce204_hw4_library.CarRentalSystem.run ()
Definition at line 106 of file CarRentalSystem.java.
                    {
    while (true) {
      System.out.println("\n**** CAR-RENT SYSTEM MENU ****\n");
      System.out.println("Add vehicle: 1");
      System.out.println("Rent vehicle: 2");
      System.out.println("Return vehicle: 3");
      System.out.println("Vehicle Maintenance: 4");
      System.out.println("Complete Maintenance: 5");
      System.out.println("Display All Vehicles: 6");
      System.out.println("Log Out: 7");
      System.out.println("Exit Program: 8");
      System.out.print("Enter your choice: ");
      Scanner sc= new Scanner(System.in);
      int choice = sc.nextInt();
      sc.nextLine();
      switch (choice) {
        case 1:
          this.add(sc); //Method used to add either cars or vans
          break;
        case 2:
          this.rent(sc); //Method used to rent either cars or vans
          break;
        case 3:
          this.returnCar(sc); //Method used to return a car after being rented
          break;
        case 4:
          this.vehicleMaintenance(sc); //Method used to set either car or van to maintenance
          break;
        case 5:
          this.completeMaintenance(sc); //Method used to complete the maintenance
          break;
        case 6:
          this.getDetails(); //Method used to get the details of cars or vans if present
          break;
        case 7:
          loginPage();
          return;
        case 8:
          sc.close(); //Closing the scanner if 7 is selected by the user
          return;
        default:
          System.out.println("Please try again.");
          break;
      }
    }
  }
References ce204_hw4_library.CarRentalSystem.loginPage().
Referenced by ce204_hw4_library.CarRentalSystem.loginPage().
Member Data Documentation
format
DateFormat ce204_hw4_library.CarRentalSystem.format = new SimpleDateFormat(`dd/MM/yyyy`) [static]
Definition at line 18 of file CarRentalSystem.java.
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/CarRentalSystem.java