ce204_hw4_library.Van Class Reference
Public Member Functions
 Van
Parameters
 in vehicleId [String]
 in year [int]
 in make [String]
 in model [String]
 in status [int]
 in vehicleType [VehicleType]
Return values
[
Van (String vehicleId, int year, String make, String model, int status, VehicleType vehicleType)
 getVehicleId
Return values
[
String getVehicleId ()
 getYear
Return values
[
int getYear ()
 getMake
Return values
[
String getMake ()
 getModel
Return values
[
String getModel ()
 getStatus
Return values
[
int getStatus ()
 getVehicleType
Return values
[
VehicleType getVehicleType ()
 setVehicleStatus
Parameters
 in status [int] Specifies the tool add rental record
void setVehicleStatus (int status)
 addRentalRecord
Parameters
 in rentalRecord [RentalRecord] Specifies the tool add rental record
void addRentalRecord (RentalRecord rentalRecord)
 getRentalRecords
Return values
[
RentalRecord[] getRentalRecords ()
 getLateFee
Parameters
 in endDate [DateTime]
 in startDate [DateTime]
Return values
[
double getLateFee (DateTime endDate, DateTime startDate)
 returnVehicle
Parameters
 in returnDate [DateTime]
Return values
[
boolean returnVehicle (DateTime returnDate)
 completeMaintenance
Parameters
 in completionDate [DateTime]
Return values
[
boolean completeMaintenance (DateTime completionDate)
 toString
Return values
[
String toString ()
 getDetails
Return values
[
String getDetails ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file Van.java.
Constructor & Destructor Documentation
Van()
ce204_hw4_library.Van.Van (String vehicleId, int year, String make, String model, int status, VehicleType vehicleType)
Definition at line 20 of file Van.java.
                                                                                                         {
    super(vehicleId, year, make, model, status, vehicleType);
    this.rentalRecords = new RentalRecord[10];
    this.rentalRecordCount = 0;
  }
References ce204_hw4_library.Vehicle.vehicleType.
Member Function Documentation
addRentalRecord()
void ce204_hw4_library.Van.addRentalRecord (RentalRecord rentalRecord)
Definition at line 86 of file Van.java.
                                                         {
    if (rentalRecordCount < rentalRecords.length) {
      rentalRecords[rentalRecordCount] = rentalRecord;
      rentalRecordCount++;
    }
  }
completeMaintenance()
boolean ce204_hw4_library.Van.completeMaintenance (DateTime completionDate)
Definition at line 153 of file Van.java.
                                                              {
    if(this.vehicleStatus!=2 && DateTime.diffDays(completionDate,this.vehicleType.getLastMaintenance())<12)
      return false;
    this.vehicleType.setLastMaintenance(completionDate);
    this.vehicleStatus=0;
    return true;
  }
References ce204_hw4_library.DateTime.diffDays(), ce204_hw4_library.VehicleType.setLastMaintenance(), ce204_hw4_library.Vehicle.vehicleStatus, and ce204_hw4_library.Vehicle.vehicleType.
getDetails()
String ce204_hw4_library.Van.getDetails ()
Reimplemented from ce204_hw4_library.Vehicle.
Definition at line 180 of file Van.java.
                             {
    String details = super.getDetails();
    details += "\nLast maintenance date: ";
    // if (this.vehicleType.getLastMaintenance() != null) {
    // details += this.vehicleType.getLastMaintenance().toString();
    // } else {
    details += "N/A"; // Varsayılan bir mesaj veya değer
    if (this.records[0] == null) {
      details += "\nRENTAL RECORD:\nempty\n**************\n";
      // } else {
      // details += "\nRENTAL RECORD:\n**************\n";
      // int count = 0;
      // for (int index = 0; this.records[index] != null; index++) {
      // count++;
      // }
      // for (int index = count - 1; index >= 0; index--) {
      // details += this.records[index].getDetails() + " \n";
      // for (int innerIndex = 0; innerIndex < 10; innerIndex++) {
      // details += "-";
      // }
      // details += " \n";
      // }
    }
    return details;
  }
References ce204_hw4_library.Vehicle.records.
getLateFee()
double ce204_hw4_library.Van.getLateFee (DateTime endDate, DateTime startDate)
Definition at line 108 of file Van.java.
                                                                {
    if(DateTime.diffDays(endDate,startDate)>0)
      return this.lateFee* DateTime.diffDays(endDate,startDate);
    else
      return this.lateFee=0.0;
  }
References ce204_hw4_library.DateTime.diffDays().
Referenced by ce204_hw4_library.Van.returnVehicle().
getMake()
String ce204_hw4_library.Van.getMake ()
Definition at line 46 of file Van.java.
                          {
    return this.Make;
  }
References ce204_hw4_library.Vehicle.Make.
getModel()
String ce204_hw4_library.Van.getModel ()
Definition at line 54 of file Van.java.
                           {
    return this.Model;
  }
References ce204_hw4_library.Vehicle.Model.
getRentalRecords()
RentalRecord [] ce204_hw4_library.Van.getRentalRecords ()
Definition at line 97 of file Van.java.
                                           {
    return rentalRecords;
  }
Referenced by ce204_hw4_library.Van.returnVehicle().
getStatus()
int ce204_hw4_library.Van.getStatus ()
Definition at line 62 of file Van.java.
                         {
    return this.vehicleStatus;
  }
References ce204_hw4_library.Vehicle.vehicleStatus.
Referenced by ce204_hw4_library.Van.returnVehicle().
getVehicleId()
String ce204_hw4_library.Van.getVehicleId ()
Reimplemented from ce204_hw4_library.Vehicle.
Definition at line 30 of file Van.java.
                               {
    return this.Vehicle_id;
  }
References ce204_hw4_library.Vehicle.Vehicle_id.
Referenced by ce204_hw4_library.Van.returnVehicle().
getVehicleType()
VehicleType ce204_hw4_library.Van.getVehicleType ()
Definition at line 70 of file Van.java.
                                      {
    return this.vehicleType;
  }
References ce204_hw4_library.Vehicle.vehicleType.
getYear()
int ce204_hw4_library.Van.getYear ()
Definition at line 38 of file Van.java.
                       {
    return this.Year;
  }
References ce204_hw4_library.Vehicle.Year.
returnVehicle()
boolean ce204_hw4_library.Van.returnVehicle (DateTime returnDate)
Definition at line 121 of file Van.java.
                                                    {
    String vehicleType;
    if (this.getVehicleId().contains("C_"))
      vehicleType = "car";
    else
      vehicleType = "van";
    if (this.getStatus() != 0) {
      RentalRecord lastRentalRecord = this.getRentalRecords()[this.rentalRecordCount - 1];
      DateTime estimatedDate = lastRentalRecord.getEstimatedReturnDate();
      DateTime rentDate = lastRentalRecord.getRentDate();
      if (vehicleType.equals("van") && DateTime.diffDays(returnDate, rentDate) < 1) {
        return false;
      } else {
        double rent = this.rate * DateTime.diffDays(returnDate, rentDate);
        double lateFee = this.getLateFee(returnDate, estimatedDate);
        this.setVehicleStatus(0);
        return true;
      }
    } else {
      return false;
    }
  }
References ce204_hw4_library.DateTime.diffDays(), ce204_hw4_library.RentalRecord.getEstimatedReturnDate(), ce204_hw4_library.Van.getLateFee(), ce204_hw4_library.Van.getRentalRecords(), ce204_hw4_library.RentalRecord.getRentDate(), ce204_hw4_library.Van.getStatus(), ce204_hw4_library.Van.getVehicleId(), ce204_hw4_library.Vehicle.rent(), ce204_hw4_library.Van.setVehicleStatus(), and ce204_hw4_library.Vehicle.vehicleType.
setVehicleStatus()
void ce204_hw4_library.Van.setVehicleStatus (int status)
Definition at line 78 of file Van.java.
                                           {
    this.vehicleStatus = status;
  }
References ce204_hw4_library.Vehicle.vehicleStatus.
Referenced by ce204_hw4_library.Van.returnVehicle().
toString()
String ce204_hw4_library.Van.toString ()
Reimplemented from ce204_hw4_library.Vehicle.
Definition at line 167 of file Van.java.
                           {
    String details = super.toString();
    DateTime lastMaintenanceDate= this.vehicleType.getLastMaintenance();
    details += ":"+ lastMaintenanceDate.toString();
    return details;
  }
References ce204_hw4_library.VehicleType.getLastMaintenance(), ce204_hw4_library.DateTime.toString(), and ce204_hw4_library.Vehicle.vehicleType.
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/Van.java