ce204_hw4_library.Car Class Reference
Public Member Functions
 Car
Parameters
 in VehicleId [String]
 in Year [int]
 in Make [String]
 in Model [String]
 in status [int]
 in vehicleType [VehicleType] Class to save all the car details This class contains all the calculations and details of the car It extends Vehicle so it has all the features of a vehicle
Car (String VehicleId, int Year, String Make, String Model, int status, VehicleType vehicleType)
 getYear
Return values
[
int getYear ()
 getMake
Return values
[
String getMake ()
 getModel
Return values
[
String getModel ()
 setVehicleStatus
Parameters
 in status [int] Used to add either cars or vans to the list
void setVehicleStatus (int status)
 getVehicleStatus
Return values
[
int getVehicleStatus ()
 getVehicleType
Return values
[
VehicleType getVehicleType ()
 addRentalRecord
Parameters
 in rentalRecord [RentalRecord] Used to add either cars or vans to the list
void addRentalRecord (RentalRecord rentalRecord)
 getRentalRecords
Parameters
 in rentalRecord [RentalRecord]
Return values
[
RentalRecord[] getRentalRecords ()
 getLateFee
Parameters
 in endDate [DateTime]
 in startDate [DateTime]
Return values
[
double getLateFee (DateTime endDate, DateTime startDate)
 returnVehicle
Parameters
 in returnDate [DateTime]
Return values
[
boolean returnVehicle (DateTime returnDate)
 completeMaintenance
Parameters
 in completionDate [DateTime]
Return values
[
boolean completeMaintenance (DateTime completionDate)
 toString
Return values
[
String toString ()
 getDetails
Return values
[
String getDetails ()
Additional Inherited Members
Detailed Description
Definition at line 4 of file Car.java.
Constructor & Destructor Documentation
Car()
ce204_hw4_library.Car.Car (String VehicleId, int Year, String Make, String Model, int status, VehicleType vehicleType)
Definition at line 24 of file Car.java.
                                                                                                    {
    super(VehicleId,Year,Make,Model,status,vehicleType);
    this.rentalRecords = new RentalRecord[10];
    this.rentalRecordCount = 0;
    seats=vehicleType.getCarSeats();
  }
References ce204_hw4_library.VehicleType.getCarSeats(), ce204_hw4_library.Vehicle.Make, ce204_hw4_library.Vehicle.Model, ce204_hw4_library.Vehicle.vehicleType, and ce204_hw4_library.Vehicle.Year.
Member Function Documentation
addRentalRecord()
void ce204_hw4_library.Car.addRentalRecord (RentalRecord rentalRecord)
Definition at line 83 of file Car.java.
                                                         {
    if (rentalRecordCount < rentalRecords.length) {
      rentalRecords[rentalRecordCount] = rentalRecord;
      rentalRecordCount++;
    }
  }
completeMaintenance()
boolean ce204_hw4_library.Car.completeMaintenance (DateTime completionDate)
Definition at line 151 of file Car.java.
                                                              {
    if(this.vehicleStatus!=2 && DateTime.diffDays(completionDate,this.vehicleType.getLastMaintenance())<12)
      return false;
    this.vehicleType.setLastMaintenance(completionDate);
    this.vehicleStatus=0;
    return true;
  }
References ce204_hw4_library.DateTime.diffDays(), ce204_hw4_library.VehicleType.setLastMaintenance(), ce204_hw4_library.Vehicle.vehicleStatus, and ce204_hw4_library.Vehicle.vehicleType.
getDetails()
String ce204_hw4_library.Car.getDetails ()
Reimplemented from ce204_hw4_library.Vehicle.
Definition at line 180 of file Car.java.
                             {
    String details = super.getDetails();
    details += "\nLast maintenance date: ";
    // if (this.vehicleType.getLastMaintenance() != null) {
    // details += this.vehicleType.getLastMaintenance().toString();
    // } else {
    details += "N/A"; // Varsayılan bir mesaj veya değer
    if (this.records[0] == null) {
      details += "\nRENTAL RECORD:\nempty\n**************\n";
      // } else {
      // details += "\nRENTAL RECORD:\n**************\n";
      // int count = 0;
      // for (int index = 0; this.records[index] != null; index++) {
      // count++;
      // }
      // for (int index = count - 1; index >= 0; index--) {
      // details += this.records[index].getDetails() + " \n";
      // for (int innerIndex = 0; innerIndex < 10; innerIndex++) {
      // details += "-";
      // }
      // details += " \n";
      // }
    }
    return details;
  }
References ce204_hw4_library.Vehicle.records.
getLateFee()
double ce204_hw4_library.Car.getLateFee (DateTime endDate, DateTime startDate)
Definition at line 106 of file Car.java.
                                                                {
    if(DateTime.diffDays(endDate,startDate)>0)
      return this.lateFee* DateTime.diffDays(endDate,startDate);
    else
      return this.lateFee=0.0;
  }
References ce204_hw4_library.DateTime.diffDays().
Referenced by ce204_hw4_library.Car.returnVehicle().
getMake()
String ce204_hw4_library.Car.getMake ()
Definition at line 43 of file Car.java.
                          {
    return this.Make;
  }
References ce204_hw4_library.Vehicle.Make.
getModel()
String ce204_hw4_library.Car.getModel ()
Definition at line 51 of file Car.java.
                           {
    return this.Model;
  }
References ce204_hw4_library.Vehicle.Model.
getRentalRecords()
RentalRecord [] ce204_hw4_library.Car.getRentalRecords ()
Definition at line 95 of file Car.java.
                                           {
    return rentalRecords;
  }
Referenced by ce204_hw4_library.Car.returnVehicle().
getVehicleStatus()
int ce204_hw4_library.Car.getVehicleStatus ()
Definition at line 67 of file Car.java.
                                {
    return this.vehicleStatus;
  }
References ce204_hw4_library.Vehicle.vehicleStatus.
Referenced by ce204_hw4_library.Car.returnVehicle().
getVehicleType()
VehicleType ce204_hw4_library.Car.getVehicleType ()
Definition at line 75 of file Car.java.
                                      {
    return this.vehicleType;
  }
References ce204_hw4_library.Vehicle.vehicleType.
getYear()
int ce204_hw4_library.Car.getYear ()
Definition at line 35 of file Car.java.
                       {
    return this.Year;
  }
References ce204_hw4_library.Vehicle.Year.
returnVehicle()
boolean ce204_hw4_library.Car.returnVehicle (DateTime returnDate)
Definition at line 119 of file Car.java.
                                                    {
    String vehicleType;
    if (this.getVehicleId().contains("C_"))
      vehicleType = "car";
    else
      vehicleType = "van";
    if (this.getVehicleStatus() != 0) {
      RentalRecord lastRentalRecord = this.getRentalRecords()[this.rentalRecordCount - 1];
      DateTime estimatedDate = lastRentalRecord.getEstimatedReturnDate();
      DateTime rentDate = lastRentalRecord.getRentDate();
      if (vehicleType.equals("van") && DateTime.diffDays(returnDate, rentDate) < 1) {
        return false;
      } else {
        double rent = this.rate * DateTime.diffDays(returnDate, rentDate);
        double lateFee = this.getLateFee(returnDate, estimatedDate);
        this.setVehicleStatus(0);
        return true;
      }
    } else {
      return false;
    }
  }
References ce204_hw4_library.DateTime.diffDays(), ce204_hw4_library.RentalRecord.getEstimatedReturnDate(), ce204_hw4_library.Car.getLateFee(), ce204_hw4_library.Car.getRentalRecords(), ce204_hw4_library.RentalRecord.getRentDate(), ce204_hw4_library.Vehicle.getVehicleId(), ce204_hw4_library.Car.getVehicleStatus(), ce204_hw4_library.Vehicle.rent(), ce204_hw4_library.Car.setVehicleStatus(), and ce204_hw4_library.Vehicle.vehicleType.
setVehicleStatus()
void ce204_hw4_library.Car.setVehicleStatus (int status)
Definition at line 59 of file Car.java.
                                           {
    this.vehicleStatus = status;
  }
References ce204_hw4_library.Vehicle.vehicleStatus.
Referenced by ce204_hw4_library.Car.returnVehicle().
toString()
String ce204_hw4_library.Car.toString ()
Reimplemented from ce204_hw4_library.Vehicle.
Definition at line 167 of file Car.java.
                           {
    String details = super.toString();
    DateTime lastMaintenanceDate= this.vehicleType.getLastMaintenance();
    details += ":"+ lastMaintenanceDate.toString();
    return details;
  }
References ce204_hw4_library.VehicleType.getLastMaintenance(), ce204_hw4_library.DateTime.toString(), and ce204_hw4_library.Vehicle.vehicleType.
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/Car.java