ce204_hw4_library.VehicleType Class Reference
Public Member Functions
 VehicleType
Parameters
 in LastMaintenance [DateTime]
 in seats [int] Declarations for all attributes that belong in this class.
VehicleType (int seats)
VehicleType (int seats, DateTime LastMaintenance)
 getSeats
Parameters
 in type [String]
Return values
[
int getSeats (String type)
 getCarSeats
Return values
[
int getCarSeats ()
 setCarSeats
Parameters
 in seats [int] method to set seats of vehicle by accepting seats
void setCarSeats (int seats)
 indexOf
Parameters
 in day [String]
Return values
[
int indexOf (String day)
 getLastMaintenance
Return values
[
DateTime getLastMaintenance ()
 setLastMaintenance
Parameters
 in day [DateTime] Lists in Java are ordered collection of data
void setLastMaintenance (DateTime date)
 canBeRentedForMinimumDays
Parameters
 in date [DateTime]
 in type [String]
Return values
[
int canBeRentedForMinimumDays (DateTime date, String type)
 IsUnderMaintenance
Parameters
 in rentDate [DateTime]
 in type [String]
 in numOfRentDays [int]
Return values
[
boolean IsUnderMaintenance (DateTime rentDate, String type, int numOfRentDays)
Detailed Description
Definition at line 3 of file VehicleType.java.
Constructor & Destructor Documentation
VehicleType() [1/2]
ce204_hw4_library.VehicleType.VehicleType (int seats)
Definition at line 17 of file VehicleType.java.
                                {
    this.carSeats=seats;
  }
VehicleType() [2/2]
ce204_hw4_library.VehicleType.VehicleType (int seats, DateTime LastMaintenance)
Definition at line 27 of file VehicleType.java.
                                                         {
    this.vanSeats=seats;
    this.LastMaintenance=LastMaintenance;
  }
Member Function Documentation
canBeRentedForMinimumDays()
int ce204_hw4_library.VehicleType.canBeRentedForMinimumDays (DateTime date, String type)
Definition at line 104 of file VehicleType.java.
                                                                  {
    // if(this.indexOf(date.getNameOfDay())+1<=5 && this.indexOf(date.getNameOfDay())+1>=1 && type.equals("car")){
    // return 2;
    // }
    if(type.equals("car")) {
      return 3;
    } else {
      return 1; //van can be rented only 1 day
    }
  }
Referenced by ce204_hw4_library.Vehicle.rent().
getCarSeats()
int ce204_hw4_library.VehicleType.getCarSeats ()
Definition at line 51 of file VehicleType.java.
                           {
    return this.carSeats;
  }
Referenced by ce204_hw4_library.Car.Car().
getLastMaintenance()
DateTime ce204_hw4_library.VehicleType.getLastMaintenance ()
Definition at line 83 of file VehicleType.java.
                                       {
    return this.LastMaintenance;
  }
Referenced by ce204_hw4_library.Car.toString(), and ce204_hw4_library.Van.toString().
getSeats()
int ce204_hw4_library.VehicleType.getSeats (String type)
Definition at line 38 of file VehicleType.java.
                                   {
    if(type.equals("car")) {
      return this.carSeats;
    } else {
      return this.vanSeats;
    }
  }
Referenced by ce204_hw4_library.Vehicle.getDetails().
indexOf()
int ce204_hw4_library.VehicleType.indexOf (String day)
Definition at line 70 of file VehicleType.java.
                                 {
    for(int index=0; index<days.length; index++)
      if(days[index].equals(day))
        return index;
    return 0;
  }
IsUnderMaintenance()
boolean ce204_hw4_library.VehicleType.IsUnderMaintenance (DateTime rentDate, String type, int numOfRentDays)
Definition at line 123 of file VehicleType.java.
                                                                                     {
    DateTime nextMaintenance=new DateTime(this.LastMaintenance,12);
    // if(type.equals("van") && DateTime.diffDays(nextMaintenance,new DateTime(rentDate,numOfRentDays))>=0 && numOfRentDays<=12)
    // {
    // return false;
    // }
    if(type.equals("car")) {
      return false;
    } else {
      return true;
    }
  }
setCarSeats()
void ce204_hw4_library.VehicleType.setCarSeats (int seats)
Definition at line 60 of file VehicleType.java.
                                     {
    this.carSeats=seats;
  }
setLastMaintenance()
void ce204_hw4_library.VehicleType.setLastMaintenance (DateTime date)
Definition at line 92 of file VehicleType.java.
                                                {
    this.LastMaintenance=date;
  }
Referenced by ce204_hw4_library.Car.completeMaintenance(), and ce204_hw4_library.Van.completeMaintenance().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/VehicleType.java