ce204_hw4_library.RentalRecord Class Reference
Public Member Functions
 RentalRecord
Parameters
 in RentId [String]
 in Rentdate [DateTime]
 in EstimatedReturnDate [DateTime] The use of car rental management system can standardize the management and operation of enterprises
RentalRecord (String RentId, DateTime Rentdate, DateTime EstimatedReturnDate)
 setData
Parameters
 in ActualDate [DateTime]
 in RentalFee [Double]
 in LateFee [Double] Car rental management system is a simple and easy-to-use system for car rental companies
void setData (DateTime ActualDate, Double RentalFee, Double LateFee)
 getEstimatedReturnDate
Return values
[
DateTime getEstimatedReturnDate ()
 getRentDate
Return values
[
DateTime getRentDate ()
 getReturnDate
Return values
[
DateTime getReturnDate ()
 toString
Return values
[
String toString ()
 getDetails
Return values
[
String getDetails ()
Additional Inherited Members
Detailed Description
Definition at line 3 of file RentalRecord.java.
Constructor & Destructor Documentation
RentalRecord()
ce204_hw4_library.RentalRecord.RentalRecord (String RentId, DateTime Rentdate, DateTime EstimatedReturnDate)
Definition at line 18 of file RentalRecord.java.
                                                                                    {
    this.RentId=RentId;
    this.RentDate=Rentdate;
    this.EstimatedReturnDate=EstimatedReturnDate;
  }
Member Function Documentation
getDetails()
String ce204_hw4_library.RentalRecord.getDetails ()
Definition at line 77 of file RentalRecord.java.
                             {
    if(this.ActualReturnDate==null && this.RentalFee==null && this.LateFee==null) {
      String data =
        "Record ID: " + this.RentId
        + "\nRent Date: " + this.RentDate.toString()
        + "\nEstimated Return Date: " + this.EstimatedReturnDate.toString();
      return data;
    } else {
      return "";
    }
  }
References ce204_hw4_library.DateTime.toString().
getEstimatedReturnDate()
DateTime ce204_hw4_library.RentalRecord.getEstimatedReturnDate ()
Definition at line 40 of file RentalRecord.java.
                                           {
    return this.EstimatedReturnDate;
  }
Referenced by ce204_hw4_library.Car.returnVehicle(), and ce204_hw4_library.Van.returnVehicle().
getRentDate()
DateTime ce204_hw4_library.RentalRecord.getRentDate ()
Definition at line 48 of file RentalRecord.java.
                                {
    return this.RentDate;
  }
Referenced by ce204_hw4_library.Car.returnVehicle(), and ce204_hw4_library.Van.returnVehicle().
getReturnDate()
DateTime ce204_hw4_library.RentalRecord.getReturnDate ()
Definition at line 56 of file RentalRecord.java.
                                  {
    return returnDate;
  }
setData()
void ce204_hw4_library.RentalRecord.setData (DateTime ActualDate, Double RentalFee, Double LateFee)
Definition at line 30 of file RentalRecord.java.
                                                                           {
    this.ActualReturnDate=ActualDate;
    this.RentalFee=RentalFee;
    this.LateFee=LateFee;
  }
toString()
String ce204_hw4_library.RentalRecord.toString ()
Reimplemented from ce204_hw4_library.DateTime.
Definition at line 64 of file RentalRecord.java.
                           {
    if(this.ActualReturnDate==null && this.RentalFee==null && this.LateFee==null) {
      String data = this.RentId+":"+this.RentDate.toString()+":"+this.EstimatedReturnDate.toString()+":none:none:none";
      return data;
    } else {
      return this.RentId+":"+this.RentDate.toString()+":"+this.EstimatedReturnDate.toString()+":"+this.ActualReturnDate.toString()+":"+this.RentalFee.toString()+":"+this.LateFee.toString();
    }
  }
References ce204_hw4_library.DateTime.toString().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/RentalRecord.java