ce204_hw4_library.DateTime Class Reference
Public Member Functions
 DateTime
Parameters
 in day [int]
 in month [int]
 in year [int] It could also be used to create a digital clock, as shown in the following example.
DateTime ()
DateTime (int setClockForwardInDays)
DateTime (DateTime startDate, int setClockForwardInDays)
DateTime (int day, int month, int year)
 getTime
Return values
[
long getTime ()
 getNameOfDay
Return values
[
String getNameOfDay ()
 toString
Return values
[
String toString ()
 getFormattedDate
Return values
[
String getFormattedDate ()
 getEightDigitDate
Return values
[
String getEightDigitDate ()
 setAdvance
Parameters
 in days [int]
 in hours [int]
 in mins [int] Constructs an instance from datetime field values using the specified chronology.
void setAdvance (int days, int hours, int mins)
 equals
Parameters
 in obj [Object]
Return values
[
boolean equals (Object obj)
 hashCode
Return values
[
int hashCode ()
Static Public Member Functions
 getCurrentTime
Return values
[
static String getCurrentTime ()
 diffDays
Parameters
 in endDate [DateTime]
 in startDate [DateTime]
Return values
[
static int diffDays (DateTime endDate, DateTime startDate)
Detailed Description
Definition at line 8 of file DateTime.java.
Constructor & Destructor Documentation
DateTime() [1/4]
ce204_hw4_library.DateTime.DateTime ()
Definition at line 20 of file DateTime.java.
                    {
    time = System.currentTimeMillis();
  }
DateTime() [2/4]
ce204_hw4_library.DateTime.DateTime (int setClockForwardInDays)
Definition at line 28 of file DateTime.java.
                                             {
    advance = ((setClockForwardInDays * 24L + 0) * 60L) * 60000L;
    time = System.currentTimeMillis() + advance;
  }
DateTime() [3/4]
ce204_hw4_library.DateTime.DateTime (DateTime startDate, int setClockForwardInDays)
Definition at line 38 of file DateTime.java.
                                                                 {
    advance = ((setClockForwardInDays * 24L + 0) * 60L) * 60000L;
    time = startDate.getTime() + advance;
  }
References ce204_hw4_library.DateTime.getTime().
DateTime() [4/4]
ce204_hw4_library.DateTime.DateTime (int day, int month, int year)
Definition at line 49 of file DateTime.java.
                                                {
    setDate(day, month, year);
  }
Member Function Documentation
diffDays()
static int ce204_hw4_library.DateTime.diffDays (DateTime endDate, DateTime startDate) [static]
Definition at line 117 of file DateTime.java.
                                                                   {
    final long HOURS_IN_DAY = 24L;
    final int MINUTES_IN_HOUR = 60;
    final int SECONDS_IN_MINUTES = 60;
    final int MILLISECONDS_IN_SECOND = 1000;
    long convertToDays = HOURS_IN_DAY * MINUTES_IN_HOUR * SECONDS_IN_MINUTES * MILLISECONDS_IN_SECOND;
    long hirePeriod = endDate.getTime() - startDate.getTime();
    double difference = (double) hirePeriod / (double) convertToDays;
    int round = (int) Math.round(difference);
    return round;
  }
References ce204_hw4_library.DateTime.getTime().
Referenced by ce204_hw4_library.Car.completeMaintenance(), ce204_hw4_library.Van.completeMaintenance(), ce204_hw4_library.Car.getLateFee(), ce204_hw4_library.Van.getLateFee(), ce204_hw4_library.Car.returnVehicle(), and ce204_hw4_library.Van.returnVehicle().
equals()
boolean ce204_hw4_library.DateTime.equals (Object obj)
Definition at line 161 of file DateTime.java.
                                    {
    if (this == obj) {
      return true;
    }
    // if (obj == null || getClass() != obj.getClass()) {
    // return false;
    // }
    // DateTime other = (DateTime) obj;
    return true;
    // return this.day == other.day && this.month == other.month && this.year == other.year;
  }
getCurrentTime()
static String ce204_hw4_library.DateTime.getCurrentTime () [static]
Definition at line 82 of file DateTime.java.
                                        {
    Date date = new Date(System.currentTimeMillis()); // returns current Date/Time
    return date.toString();
  }
getEightDigitDate()
String ce204_hw4_library.DateTime.getEightDigitDate ()
Definition at line 102 of file DateTime.java.
                                    {
    SimpleDateFormat sdf = new SimpleDateFormat("ddMMyyyy");
    long currentTime = getTime();
    Date gct = new Date(currentTime);
    return sdf.format(gct);
  }
References ce204_hw4_library.DateTime.getTime().
getFormattedDate()
String ce204_hw4_library.DateTime.getFormattedDate ()
Definition at line 91 of file DateTime.java.
                                   {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    long currentTime = getTime();
    Date gct = new Date(currentTime);
    return sdf.format(gct);
  }
References ce204_hw4_library.DateTime.getTime().
Referenced by ce204_hw4_library.DateTime.toString().
getNameOfDay()
String ce204_hw4_library.DateTime.getNameOfDay ()
Definition at line 65 of file DateTime.java.
                               {
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE", Locale.ENGLISH);
        return sdf.format(time);
    }
getTime()
long ce204_hw4_library.DateTime.getTime ()
Definition at line 57 of file DateTime.java.
                        {
    return time;
  }
Referenced by ce204_hw4_library.DateTime.DateTime(), ce204_hw4_library.DateTime.diffDays(), ce204_hw4_library.DateTime.getEightDigitDate(), and ce204_hw4_library.DateTime.getFormattedDate().
hashCode()
int ce204_hw4_library.DateTime.hashCode ()
Definition at line 180 of file DateTime.java.
                        {
    return Objects.hash(day, month, year);
  }
setAdvance()
void ce204_hw4_library.DateTime.setAdvance (int days, int hours, int mins)
Definition at line 150 of file DateTime.java.
                                                        {
    advance = ((days * 24L + hours) * 60L) * 60000L;
  }
toString()
String ce204_hw4_library.DateTime.toString ()
Reimplemented in ce204_hw4_library.RentalRecord.
Definition at line 74 of file DateTime.java.
                           {
    return getFormattedDate();
  }
References ce204_hw4_library.DateTime.getFormattedDate().
Referenced by ce204_hw4_library.RentalRecord.getDetails(), ce204_hw4_library.Car.toString(), ce204_hw4_library.RentalRecord.toString(), and ce204_hw4_library.Van.toString().
The documentation for this class was generated from the following file:
ce204-hw4/src/main/java/ce204_hw4_library/DateTime.java